/**
 * The episodes that ship with the app.
 *
 * The point of these is that the shelf is never empty and never waiting:
 * they need no API key, no quota and no network, so a learner can open the
 * Podcast tab and start listening immediately. AI-written episodes are
 * added alongside them whenever the learner asks for a new one.
 *
 * Each episode is original writing for this app, built the same way the
 * generator is asked to build one: short spoken sentences, a warm first
 * person voice, a question to the listener here and there, and a small set
 * of new words that comes back at least three times so it sticks from
 * context rather than from a list.
 */

import type { Language, Level, PodcastEpisode } from './types';

/** Ordered easiest first within each language. */
export const BUILT_IN_EPISODES: PodcastEpisode[] = [
  {
    id: "built-in-de-mein-tag",
    title: "Mein Tag",
    topicEn: "Daily routine",
    language: "de",
    level: "A1",
    vocab: [
      { term: "aufstehen", en: "to get up" },
      { term: "früh", en: "early" },
      { term: "müde", en: "tired" },
      { term: "das Frühstück", en: "breakfast" },
      { term: "die Arbeit", en: "work" },
      { term: "das Abendessen", en: "dinner" },
    ],
    lines: [
      { de: "Hallo! Heute erzähle ich von meinem Tag.", en: "Hello! Today I'm telling you about my day." },
      { de: "Ich stehe jeden Morgen früh auf.", en: "I get up early every morning." },
      { de: "Mein Wecker klingelt um sechs Uhr.", en: "My alarm rings at six o’clock." },
      { de: "Dann bin ich noch sehr müde.", en: "I'm still very tired then." },
      { de: "Aufstehen ist am Montag besonders schwer.", en: "Getting up is especially hard on Monday." },
      { de: "Zuerst trinke ich einen Kaffee.", en: "First I drink a coffee." },
      { de: "Danach mache ich das Frühstück.", en: "After that I make breakfast." },
      { de: "Zum Frühstück esse ich Brot mit Käse.", en: "For breakfast I eat bread with cheese." },
      { de: "Mein Frühstück ist immer klein.", en: "My breakfast is always small." },
      { de: "Um sieben Uhr gehe ich aus dem Haus.", en: "At seven I leave the house." },
      { de: "Ich fahre mit dem Bus zur Arbeit.", en: "I take the bus to work." },
      { de: "Die Arbeit beginnt um acht Uhr.", en: "Work starts at eight." },
      { de: "Bei der Arbeit sitze ich am Computer.", en: "At work I sit at the computer." },
      { de: "Ich schreibe E-Mails und telefoniere viel.", en: "I write emails and make a lot of calls." },
      { de: "Mittags esse ich mit Kollegen.", en: "At midday I eat with colleagues." },
      { de: "Wann stehst du am Morgen auf?", en: "When do you get up in the morning?" },
      { de: "Am Nachmittag trinke ich noch einen Kaffee.", en: "In the afternoon I drink another coffee." },
      { de: "Um fünf Uhr ist die Arbeit fertig.", en: "At five work is done." },
      { de: "Dann bin ich oft sehr müde.", en: "Then I'm often very tired." },
      { de: "Ich gehe eine halbe Stunde spazieren.", en: "I go for a half-hour walk." },
      { de: "Danach koche ich das Abendessen.", en: "After that I cook dinner." },
      { de: "Zum Abendessen mag ich Suppe oder Nudeln.", en: "For dinner I like soup or noodles." },
      { de: "Das Abendessen ist meine liebste Mahlzeit.", en: "Dinner is my favourite meal." },
      { de: "Am Abend lese ich oder sehe fern.", en: "In the evening I read or watch TV." },
      { de: "Ich gehe nicht sehr früh ins Bett.", en: "I don't go to bed very early." },
      { de: "Aber morgen muss ich wieder früh aufstehen.", en: "But tomorrow I have to get up early again." },
      { de: "Und dann bin ich wieder müde.", en: "And then I'll be tired again." },
      { de: "Wie ist dein Tag? Erzähl es mir!", en: "What's your day like? Tell me!" },
    ],
  },
  {
    id: "built-in-de-einkaufen",
    title: "Einkaufen im Supermarkt",
    topicEn: "Shopping",
    language: "de",
    level: "A1",
    vocab: [
      { term: "einkaufen", en: "to shop" },
      { term: "das Gemüse", en: "vegetables" },
      { term: "billig", en: "cheap" },
      { term: "teuer", en: "expensive" },
      { term: "das Angebot", en: "special offer" },
      { term: "die Kasse", en: "the till" },
      { term: "die Tüte", en: "bag" },
    ],
    lines: [
      { de: "Heute gehe ich einkaufen.", en: "Today I'm going shopping." },
      { de: "Ich gehe fast jeden Tag einkaufen.", en: "I go shopping almost every day." },
      { de: "Mein Supermarkt ist gleich um die Ecke.", en: "My supermarket is just around the corner." },
      { de: "Er öffnet um sieben Uhr morgens.", en: "It opens at seven in the morning." },
      { de: "Am Sonntag ist er zu.", en: "On Sunday it's closed." },
      { de: "Zuerst nehme ich einen Einkaufswagen.", en: "First I take a trolley." },
      { de: "Ich brauche Obst und Gemüse.", en: "I need fruit and vegetables." },
      { de: "Das Gemüse ist hier ganz frisch.", en: "The vegetables here are very fresh." },
      { de: "Tomaten und Gurken sind gerade billig.", en: "Tomatoes and cucumbers are cheap right now." },
      { de: "Im Sommer ist Gemüse oft billig.", en: "In summer vegetables are often cheap." },
      { de: "Billig ist gut, aber frisch ist besser.", en: "Cheap is good, but fresh is better." },
      { de: "Fleisch kaufe ich nur selten.", en: "I rarely buy meat." },
      { de: "Es ist mir meistens zu teuer.", en: "It's usually too expensive for me." },
      { de: "Käse ist auch teuer, aber ich liebe Käse.", en: "Cheese is expensive too, but I love cheese." },
      { de: "Heute gibt es ein Angebot bei Milch.", en: "Today there's an offer on milk." },
      { de: "Ich schaue immer nach einem Angebot.", en: "I always look for an offer." },
      { de: "Ein gutes Angebot macht mich glücklich.", en: "A good offer makes me happy." },
      { de: "Kaufst du gern im Supermarkt ein?", en: "Do you like shopping at the supermarket?" },
      { de: "Brot kaufe ich nicht hier.", en: "I don't buy bread here." },
      { de: "Das Brot beim Bäcker ist besser.", en: "The bread at the baker's is better." },
      { de: "Dort ist es aber etwas teuer.", en: "But there it's a bit expensive." },
      { de: "Dann gehe ich zur Kasse.", en: "Then I go to the till." },
      { de: "An der Kasse ist eine lange Schlange.", en: "At the till there's a long queue." },
      { de: "Ich warte fünf Minuten an der Kasse.", en: "I wait five minutes at the till." },
      { de: "Ich bezahle mit Karte.", en: "I pay by card." },
      { de: "Meine Tüte ist aus Stoff.", en: "My bag is made of cloth." },
      { de: "Eine Tüte aus Plastik kostet hier Geld.", en: "A plastic bag costs money here." },
      { de: "Meine Tüte ist heute sehr schwer.", en: "My bag is very heavy today." },
      { de: "Zu Hause räume ich alles ein.", en: "At home I put everything away." },
      { de: "Einkaufen dauert bei mir zwanzig Minuten.", en: "Shopping takes me twenty minutes." },
      { de: "Und was kaufst du oft ein?", en: "And what do you often buy?" },
    ],
  },
  {
    id: "built-in-de-zug",
    title: "Mit dem Zug fahren",
    topicEn: "Public transport",
    language: "de",
    level: "A2",
    vocab: [
      { term: "die Fahrkarte", en: "ticket" },
      { term: "reservieren", en: "to reserve" },
      { term: "der Bahnsteig", en: "platform" },
      { term: "die Verspätung", en: "delay" },
      { term: "umsteigen", en: "to change trains" },
      { term: "pünktlich", en: "on time" },
    ],
    lines: [
      { de: "Heute fahre ich mit dem Zug nach Hamburg.", en: "Today I'm taking the train to Hamburg." },
      { de: "Ich fahre lieber Zug als Auto.", en: "I prefer the train to the car." },
      { de: "Im Zug kann ich lesen oder schlafen.", en: "On the train I can read or sleep." },
      { de: "Meine Fahrkarte habe ich online gekauft.", en: "I bought my ticket online." },
      { de: "Die Fahrkarte war im Voraus billiger.", en: "The ticket was cheaper in advance." },
      { de: "Ich zeige die Fahrkarte auf dem Handy.", en: "I show the ticket on my phone." },
      { de: "Ich habe auch einen Platz reserviert.", en: "I also reserved a seat." },
      { de: "Am Freitag sollte man immer reservieren.", en: "On Friday you should always reserve." },
      { de: "Ohne reservieren steht man manchmal im Gang.", en: "Without reserving you sometimes stand in the aisle." },
      { de: "Mein Zug fährt von Bahnsteig sieben ab.", en: "My train leaves from platform seven." },
      { de: "Der Bahnsteig ist schon voll mit Menschen.", en: "The platform is already full of people." },
      { de: "Auf dem Bahnsteig ist es kalt und windig.", en: "On the platform it's cold and windy." },
      { de: "Der Zug hat heute zehn Minuten Verspätung.", en: "The train is ten minutes late today." },
      { de: "Eine kleine Verspätung ist normal.", en: "A small delay is normal." },
      { de: "Bei einer großen Verspätung bekomme ich Geld zurück.", en: "With a big delay I get money back." },
      { de: "Fährst du oft mit dem Zug?", en: "Do you often travel by train?" },
      { de: "In Hannover muss ich umsteigen.", en: "In Hanover I have to change trains." },
      { de: "Umsteigen mag ich überhaupt nicht.", en: "I don't like changing at all." },
      { de: "Zum Umsteigen habe ich nur acht Minuten.", en: "For the change I only have eight minutes." },
      { de: "Wenn der Zug pünktlich ist, reicht das.", en: "If the train is on time, that's enough." },
      { de: "Heute ist mein Zug leider nicht pünktlich.", en: "Today my train unfortunately isn't on time." },
      { de: "Ich renne über den Bahnsteig zum anderen Zug.", en: "I run across the platform to the other train." },
      { de: "Zum Glück ist auch der zweite Zug spät.", en: "Luckily the second train is late too." },
      { de: "Manchmal hilft eine Verspätung sogar.", en: "Sometimes a delay even helps." },
      { de: "Der zweite Zug ist ruhig und fast leer.", en: "The second train is quiet and almost empty." },
      { de: "Ich trinke einen Kaffee und schaue nach draußen.", en: "I drink a coffee and look outside." },
      { de: "Nach zwei Stunden bin ich in Hamburg.", en: "After two hours I'm in Hamburg." },
      { de: "Der Zug kommt sogar pünktlich an.", en: "The train even arrives on time." },
      { de: "Wie reist du am liebsten?", en: "How do you most like to travel?" },
    ],
  },
  {
    id: "built-in-de-arzt",
    title: "Beim Arzt",
    topicEn: "Health and the doctor",
    language: "de",
    level: "A2",
    vocab: [
      { term: "der Termin", en: "appointment" },
      { term: "das Wartezimmer", en: "waiting room" },
      { term: "die Schmerzen", en: "pain" },
      { term: "das Rezept", en: "prescription" },
      { term: "die Apotheke", en: "pharmacy" },
      { term: "die Tablette", en: "tablet" },
    ],
    lines: [
      { de: "Letzte Woche ging es mir nicht gut.", en: "Last week I wasn't feeling well." },
      { de: "Mein Hals tat weh und ich hatte Fieber.", en: "My throat hurt and I had a fever." },
      { de: "Also rief ich beim Arzt an.", en: "So I called the doctor." },
      { de: "Ich brauchte schnell einen Termin.", en: "I needed an appointment quickly." },
      { de: "Einen Termin bekommt man nicht immer sofort.", en: "You don't always get an appointment straight away." },
      { de: "Mein Termin war erst am nächsten Tag.", en: "My appointment was only the next day." },
      { de: "Am Morgen fuhr ich in die Praxis.", en: "In the morning I went to the practice." },
      { de: "Im Wartezimmer saßen schon sechs Leute.", en: "Six people were already sitting in the waiting room." },
      { de: "Das Wartezimmer war klein und sehr warm.", en: "The waiting room was small and very warm." },
      { de: "Im Wartezimmer las ich eine alte Zeitschrift.", en: "In the waiting room I read an old magazine." },
      { de: "Nach zwanzig Minuten rief die Ärztin mich.", en: "After twenty minutes the doctor called me." },
      { de: "Sie fragte, wo ich Schmerzen habe.", en: "She asked where I had pain." },
      { de: "Ich hatte Schmerzen im Hals und im Kopf.", en: "I had pain in my throat and head." },
      { de: "Bei starken Schmerzen soll man nicht warten.", en: "With bad pain you shouldn't wait." },
      { de: "Die Ärztin schaute in meinen Hals.", en: "The doctor looked in my throat." },
      { de: "Es war nur eine Erkältung.", en: "It was only a cold." },
      { de: "Sie schrieb mir ein Rezept.", en: "She wrote me a prescription." },
      { de: "Mit dem Rezept ist die Medizin günstiger.", en: "With the prescription the medicine is cheaper." },
      { de: "Das Rezept kam direkt auf meine Karte.", en: "The prescription went straight onto my card." },
      { de: "Danach ging ich in die Apotheke.", en: "Then I went to the pharmacy." },
      { de: "Die Apotheke ist neben der Praxis.", en: "The pharmacy is next to the practice." },
      { de: "In der Apotheke war niemand vor mir.", en: "In the pharmacy there was nobody ahead of me." },
      { de: "Ich bekam Tabletten und einen Tee.", en: "I got tablets and a tea." },
      { de: "Die Tabletten nahm ich dreimal am Tag.", en: "I took the tablets three times a day." },
      { de: "Nach zwei Tagen half die Tablette wirklich.", en: "After two days the tablet really helped." },
      { de: "Warst du dieses Jahr schon beim Arzt?", en: "Have you been to the doctor this year?" },
      { de: "Heute geht es mir wieder gut.", en: "Today I'm well again." },
      { de: "Aber den Termin habe ich nicht vergessen.", en: "But I haven't forgotten the appointment." },
    ],
  },
  {
    id: "built-in-de-wohnung",
    title: "Eine Wohnung finden",
    topicEn: "Housing",
    language: "de",
    level: "B1",
    vocab: [
      { term: "die Miete", en: "rent" },
      { term: "die Nebenkosten", en: "additional costs" },
      { term: "die Besichtigung", en: "viewing" },
      { term: "der Vermieter", en: "landlord" },
      { term: "der Mietvertrag", en: "tenancy agreement" },
      { term: "die Kaution", en: "deposit" },
    ],
    lines: [
      { de: "Im Frühling habe ich eine neue Wohnung gesucht.", en: "In spring I looked for a new flat." },
      { de: "In meiner Stadt ist das gar nicht einfach.", en: "In my city that isn't easy at all." },
      { de: "Viele Leute suchen, und es gibt wenige Wohnungen.", en: "Many people are looking, and there are few flats." },
      { de: "Die Miete ist in den letzten Jahren stark gestiegen.", en: "Rents have risen sharply in recent years." },
      { de: "Für eine kleine Wohnung zahlt man hier viel Miete.", en: "You pay a lot of rent here for a small flat." },
      { de: "Meine alte Miete war zum Glück niedrig.", en: "My old rent was luckily low." },
      { de: "Wichtig sind auch die Nebenkosten.", en: "The additional costs matter too." },
      { de: "Zu den Nebenkosten gehören Wasser, Heizung und Müll.", en: "Water, heating and rubbish are part of the additional costs." },
      { de: "Ohne Nebenkosten sieht jede Wohnung günstig aus.", en: "Without the additional costs every flat looks cheap." },
      { de: "Ich habe zwanzig Anzeigen im Internet geschrieben.", en: "I wrote to twenty adverts online." },
      { de: "Nur vier Leute haben geantwortet.", en: "Only four people answered." },
      { de: "Dann hatte ich meine erste Besichtigung.", en: "Then I had my first viewing." },
      { de: "Bei einer Besichtigung waren dreißig andere Menschen da.", en: "At one viewing there were thirty other people." },
      { de: "Nach der Besichtigung war ich ziemlich müde.", en: "After the viewing I was rather tired." },
      { de: "Suchst du auch gerade eine Wohnung?", en: "Are you looking for a flat right now too?" },
      { de: "Bei der vierten Wohnung hat es geklappt.", en: "With the fourth flat it worked out." },
      { de: "Der Vermieter war freundlich und ruhig.", en: "The landlord was friendly and calm." },
      { de: "Der Vermieter wollte meinen Arbeitsvertrag sehen.", en: "The landlord wanted to see my employment contract." },
      { de: "Ein Vermieter fragt fast immer nach dem Einkommen.", en: "A landlord almost always asks about your income." },
      { de: "Danach kam der Mietvertrag per E-Mail.", en: "Then the tenancy agreement came by email." },
      { de: "Den Mietvertrag habe ich zweimal gelesen.", en: "I read the tenancy agreement twice." },
      { de: "Im Mietvertrag stand alles über Haustiere und Lärm.", en: "The tenancy agreement said everything about pets and noise." },
      { de: "Vor dem Umzug musste ich eine Kaution zahlen.", en: "Before moving I had to pay a deposit." },
      { de: "Die Kaution war so hoch wie drei Monatsmieten.", en: "The deposit was as high as three months' rent." },
      { de: "Am Ende bekommt man die Kaution zurück.", en: "In the end you get the deposit back." },
      { de: "Aber nur, wenn die Wohnung in Ordnung ist.", en: "But only if the flat is in good condition." },
      { de: "Jetzt wohne ich seit drei Monaten hier.", en: "Now I've been living here for three months." },
      { de: "Der Balkon ist klein, aber am Abend kommt die Sonne.", en: "The balcony is small, but in the evening the sun comes in." },
      { de: "Und das war die ganze Suche wert.", en: "And that made the whole search worth it." },
    ],
  },
  {
    id: "built-in-de-homeoffice",
    title: "Arbeiten im Homeoffice",
    topicEn: "Work and jobs",
    language: "de",
    level: "B2",
    vocab: [
      { term: "das Homeoffice", en: "working from home" },
      { term: "das Pendeln", en: "commuting" },
      { term: "die Besprechung", en: "meeting" },
      { term: "konzentrieren", en: "to concentrate" },
      { term: "die Grenze", en: "boundary" },
      { term: "der Feierabend", en: "end of the working day" },
    ],
    lines: [
      { de: "Seit vier Jahren arbeite ich meistens im Homeoffice.", en: "For four years I've mostly worked from home." },
      { de: "Am Anfang klang das Homeoffice wie ein Traum.", en: "At first working from home sounded like a dream." },
      { de: "Heute sehe ich das Homeoffice etwas nüchterner.", en: "Today I see working from home a bit more soberly." },
      { de: "Das Beste ist: das Pendeln fällt weg.", en: "The best thing is that the commute disappears." },
      { de: "Früher hat das Pendeln täglich zwei Stunden gekostet.", en: "The commute used to cost two hours a day." },
      { de: "Ohne Pendeln schlafe ich länger und esse besser.", en: "Without commuting I sleep longer and eat better." },
      { de: "Dafür ist der Tag voller Besprechungen.", en: "In exchange the day is full of meetings." },
      { de: "Eine Besprechung online ist kürzer, aber anstrengender.", en: "A meeting online is shorter but more tiring." },
      { de: "Nach der fünften Besprechung ist mein Kopf leer.", en: "After the fifth meeting my head is empty." },
      { de: "Zu Hause kann ich mich morgens gut konzentrieren.", en: "At home I can concentrate well in the mornings." },
      { de: "Am Nachmittag fällt mir das Konzentrieren deutlich schwerer.", en: "In the afternoon concentrating is clearly harder for me." },
      { de: "Wer sich konzentrieren will, braucht eine Tür.", en: "Anyone who wants to concentrate needs a door." },
      { de: "Arbeitest du auch von zu Hause?", en: "Do you work from home too?" },
      { de: "Das größte Problem ist die Grenze.", en: "The biggest problem is the boundary." },
      { de: "Die Grenze zwischen Arbeit und Freizeit verschwindet leicht.", en: "The boundary between work and free time easily disappears." },
      { de: "Ohne Grenze arbeitet man abends einfach weiter.", en: "Without a boundary you simply keep working in the evening." },
      { de: "Deshalb mache ich bewusst Feierabend.", en: "That's why I deliberately stop for the day." },
      { de: "Feierabend heißt bei mir: Laptop zu, Licht aus.", en: "Stopping for the day means: laptop closed, light off." },
      { de: "Nach dem Feierabend gehe ich eine Runde spazieren.", en: "After stopping I go for a walk." },
      { de: "Der Spaziergang ersetzt mir das Pendeln.", en: "The walk replaces the commute for me." },
      { de: "Einmal pro Woche fahre ich ins Büro.", en: "Once a week I go into the office." },
      { de: "Dort ist eine Besprechung plötzlich ein Gespräch.", en: "There a meeting suddenly becomes a conversation." },
      { de: "Man redet über das Wetter und über Projekte.", en: "You talk about the weather and about projects." },
      { de: "Danach kann ich mich zu Hause besser konzentrieren.", en: "Afterwards I can concentrate better at home." },
      { de: "Beides zusammen funktioniert für mich am besten.", en: "Both together work best for me." },
      { de: "Das Homeoffice ist kein Traum und kein Problem.", en: "Working from home is neither a dream nor a problem." },
      { de: "Es ist einfach eine Art zu arbeiten.", en: "It's simply a way of working." },
      { de: "Wie hältst du deine Grenze zwischen beidem?", en: "How do you keep your boundary between the two?" },
    ],
  },
  {
    id: "built-in-es-mi-dia",
    title: "Mi día",
    topicEn: "Daily routine",
    language: "es",
    level: "A1",
    vocab: [
      { term: "levantarse", en: "to get up" },
      { term: "temprano", en: "early" },
      { term: "cansado", en: "tired" },
      { term: "el desayuno", en: "breakfast" },
      { term: "el trabajo", en: "work" },
      { term: "la cena", en: "dinner" },
    ],
    lines: [
      { de: "¡Hola! Hoy te cuento cómo es mi día.", en: "Hi! Today I'll tell you what my day is like." },
      { de: "Me levanto temprano todos los días.", en: "I get up early every day." },
      { de: "Mi despertador suena a las seis.", en: "My alarm goes off at six." },
      { de: "A esa hora estoy muy cansada.", en: "At that time I'm very tired." },
      { de: "Levantarse el lunes es muy difícil.", en: "Getting up on Monday is very hard." },
      { de: "Primero tomo un café solo.", en: "First I have a black coffee." },
      { de: "Después preparo el desayuno.", en: "Then I make breakfast." },
      { de: "Para el desayuno como pan con tomate.", en: "For breakfast I eat bread with tomato." },
      { de: "Mi desayuno siempre es pequeño.", en: "My breakfast is always small." },
      { de: "A las siete salgo de casa.", en: "At seven I leave the house." },
      { de: "Voy al trabajo en autobús.", en: "I go to work by bus." },
      { de: "El trabajo empieza a las ocho.", en: "Work starts at eight." },
      { de: "En el trabajo escribo muchos correos.", en: "At work I write a lot of emails." },
      { de: "A la una como con mis compañeros.", en: "At one o'clock I eat with my colleagues." },
      { de: "¿Y tú, te levantas temprano?", en: "And you, do you get up early?" },
      { de: "Por la tarde tomo otro café.", en: "In the afternoon I have another coffee." },
      { de: "A las seis termino y vuelvo a casa.", en: "At six I finish and go home." },
      { de: "Entonces estoy bastante cansada.", en: "Then I'm quite tired." },
      { de: "Camino media hora por el parque.", en: "I walk for half an hour in the park." },
      { de: "Después preparo la cena.", en: "Then I make dinner." },
      { de: "Para la cena me gusta la sopa.", en: "For dinner I like soup." },
      { de: "La cena es mi comida favorita.", en: "Dinner is my favourite meal." },
      { de: "Por la noche leo un poco.", en: "At night I read a little." },
      { de: "No me acuesto muy temprano.", en: "I don't go to bed very early." },
      { de: "Pero mañana me levanto otra vez a las seis.", en: "But tomorrow I get up at six again." },
      { de: "Y otra vez estoy cansada.", en: "And again I'm tired." },
      { de: "¿Cómo es tu día? ¡Cuéntamelo!", en: "What's your day like? Tell me about it!" },
    ],
  },
  {
    id: "built-in-es-mercado",
    title: "En el mercado",
    topicEn: "Shopping",
    language: "es",
    level: "A1",
    vocab: [
      { term: "el mercado", en: "market" },
      { term: "la verdura", en: "vegetables" },
      { term: "barato", en: "cheap" },
      { term: "caro", en: "expensive" },
      { term: "la oferta", en: "special offer" },
      { term: "la bolsa", en: "bag" },
    ],
    lines: [
      { de: "Hoy voy al mercado del barrio.", en: "Today I'm going to the neighbourhood market." },
      { de: "Voy al mercado casi todos los sábados.", en: "I go to the market almost every Saturday." },
      { de: "El mercado abre a las ocho.", en: "The market opens at eight." },
      { de: "El domingo el mercado está cerrado.", en: "On Sunday the market is closed." },
      { de: "Primero compro fruta y verdura.", en: "First I buy fruit and vegetables." },
      { de: "La verdura aquí es muy fresca.", en: "The vegetables here are very fresh." },
      { de: "En verano la verdura está más barata.", en: "In summer vegetables are cheaper." },
      { de: "Los tomates están muy baratos hoy.", en: "Tomatoes are very cheap today." },
      { de: "Barato no siempre significa malo.", en: "Cheap doesn't always mean bad." },
      { de: "La carne es cara para mí.", en: "Meat is expensive for me." },
      { de: "El pescado también es caro.", en: "Fish is expensive too." },
      { de: "Solo compro pescado caro los domingos.", en: "I only buy expensive fish on Sundays." },
      { de: "Todo está más caro que el año pasado.", en: "Everything is more expensive than last year." },
      { de: "Hoy hay una oferta en el queso.", en: "Today there's an offer on cheese." },
      { de: "Siempre busco una oferta buena.", en: "I always look for a good offer." },
      { de: "Una oferta así me pone contenta.", en: "An offer like that makes me happy." },
      { de: "¿Tú compras en el mercado o en el supermercado?", en: "Do you shop at the market or the supermarket?" },
      { de: "El pan lo compro en la panadería.", en: "I buy bread at the bakery." },
      { de: "El pan de la panadería está mejor.", en: "The bakery bread is better." },
      { de: "Después hablo un poco con la vendedora.", en: "Then I chat a bit with the seller." },
      { de: "Ella siempre me da una manzana.", en: "She always gives me an apple." },
      { de: "Llevo mi propia bolsa de tela.", en: "I bring my own cloth bag." },
      { de: "Una bolsa de plástico cuesta diez céntimos.", en: "A plastic bag costs ten cents." },
      { de: "Mi bolsa hoy pesa mucho.", en: "My bag is very heavy today." },
      { de: "En casa guardo todo en la nevera.", en: "At home I put everything in the fridge." },
      { de: "Ir al mercado me gusta mucho.", en: "I really like going to the market." },
      { de: "Es más lento, pero más bonito.", en: "It's slower, but nicer." },
      { de: "¿Y tú qué compras siempre?", en: "And what do you always buy?" },
    ],
  },
  {
    id: "built-in-es-tren",
    title: "Viajar en tren",
    topicEn: "Public transport",
    language: "es",
    level: "A2",
    vocab: [
      { term: "el billete", en: "ticket" },
      { term: "reservar", en: "to reserve" },
      { term: "el andén", en: "platform" },
      { term: "el retraso", en: "delay" },
      { term: "el transbordo", en: "change of trains" },
      { term: "puntual", en: "on time" },
    ],
    lines: [
      { de: "Hoy viajo en tren a Valencia.", en: "Today I'm travelling by train to Valencia." },
      { de: "Prefiero el tren al coche.", en: "I prefer the train to the car." },
      { de: "En el tren puedo leer o dormir.", en: "On the train I can read or sleep." },
      { de: "Compré el billete por internet.", en: "I bought the ticket online." },
      { de: "El billete era más barato con antelación.", en: "The ticket was cheaper in advance." },
      { de: "Llevo el billete en el móvil.", en: "I have the ticket on my phone." },
      { de: "También reservé un asiento junto a la ventana.", en: "I also reserved a seat by the window." },
      { de: "Los viernes hay que reservar siempre.", en: "On Fridays you always have to reserve." },
      { de: "Sin reservar a veces viajas de pie.", en: "Without reserving you sometimes travel standing." },
      { de: "Mi tren sale del andén número siete.", en: "My train leaves from platform seven." },
      { de: "El andén está lleno de gente.", en: "The platform is full of people." },
      { de: "En el andén hace frío y viento.", en: "On the platform it's cold and windy." },
      { de: "Hoy el tren lleva diez minutos de retraso.", en: "Today the train is ten minutes late." },
      { de: "Un retraso pequeño es normal.", en: "A small delay is normal." },
      { de: "Con un retraso grande te devuelven el dinero.", en: "With a big delay they give you your money back." },
      { de: "¿Tú viajas mucho en tren?", en: "Do you travel by train a lot?" },
      { de: "En Zaragoza tengo que hacer transbordo.", en: "In Zaragoza I have to change trains." },
      { de: "Hacer transbordo no me gusta nada.", en: "I don't like changing trains at all." },
      { de: "Para el transbordo tengo solo ocho minutos.", en: "For the change I only have eight minutes." },
      { de: "Si el tren es puntual, es suficiente.", en: "If the train is on time, that's enough." },
      { de: "Hoy mi tren no es puntual.", en: "Today my train isn't on time." },
      { de: "Corro por el andén hasta el otro tren.", en: "I run along the platform to the other train." },
      { de: "Por suerte el segundo tren también sale tarde.", en: "Luckily the second train is also leaving late." },
      { de: "A veces un retraso ayuda.", en: "Sometimes a delay helps." },
      { de: "El segundo tren está tranquilo y casi vacío.", en: "The second train is quiet and almost empty." },
      { de: "Tomo un café y miro el paisaje.", en: "I have a coffee and watch the scenery." },
      { de: "Después de dos horas llego a Valencia.", en: "After two hours I arrive in Valencia." },
      { de: "Y el tren llega puntual.", en: "And the train arrives on time." },
      { de: "¿Cómo te gusta más viajar?", en: "How do you most like to travel?" },
    ],
  },
  {
    id: "built-in-es-medico",
    title: "En el médico",
    topicEn: "Health and the doctor",
    language: "es",
    level: "A2",
    vocab: [
      { term: "la cita", en: "appointment" },
      { term: "la sala de espera", en: "waiting room" },
      { term: "el dolor", en: "pain" },
      { term: "la receta", en: "prescription" },
      { term: "la farmacia", en: "pharmacy" },
      { term: "la pastilla", en: "tablet" },
    ],
    lines: [
      { de: "La semana pasada no me sentía bien.", en: "Last week I wasn't feeling well." },
      { de: "Me dolía la garganta y tenía fiebre.", en: "My throat hurt and I had a fever." },
      { de: "Entonces llamé al centro de salud.", en: "So I called the health centre." },
      { de: "Necesitaba una cita rápido.", en: "I needed an appointment quickly." },
      { de: "Una cita no siempre es para el mismo día.", en: "An appointment isn't always for the same day." },
      { de: "Mi cita era para el día siguiente.", en: "My appointment was for the next day." },
      { de: "Por la mañana fui al centro de salud.", en: "In the morning I went to the health centre." },
      { de: "En la sala de espera había seis personas.", en: "There were six people in the waiting room." },
      { de: "La sala de espera era pequeña y calurosa.", en: "The waiting room was small and hot." },
      { de: "En la sala de espera leí una revista vieja.", en: "In the waiting room I read an old magazine." },
      { de: "Después de veinte minutos me llamó la médica.", en: "After twenty minutes the doctor called me." },
      { de: "Me preguntó dónde tenía dolor.", en: "She asked me where I had pain." },
      { de: "Tenía dolor de garganta y de cabeza.", en: "I had a sore throat and a headache." },
      { de: "Con mucho dolor no hay que esperar.", en: "With a lot of pain you shouldn't wait." },
      { de: "La médica me miró la garganta.", en: "The doctor looked at my throat." },
      { de: "Era solo un resfriado.", en: "It was only a cold." },
      { de: "Me hizo una receta.", en: "She wrote me a prescription." },
      { de: "Con la receta la medicina es más barata.", en: "With the prescription the medicine is cheaper." },
      { de: "La receta fue directa a mi tarjeta sanitaria.", en: "The prescription went straight to my health card." },
      { de: "Después fui a la farmacia.", en: "Then I went to the pharmacy." },
      { de: "La farmacia está al lado del centro.", en: "The pharmacy is next to the centre." },
      { de: "En la farmacia no había nadie.", en: "There was nobody in the pharmacy." },
      { de: "Me dieron pastillas y un jarabe.", en: "They gave me tablets and a syrup." },
      { de: "Tomé las pastillas tres veces al día.", en: "I took the tablets three times a day." },
      { de: "Después de dos días la pastilla ayudó.", en: "After two days the tablet helped." },
      { de: "¿Has ido al médico este año?", en: "Have you been to the doctor this year?" },
      { de: "Hoy ya estoy bien otra vez.", en: "Today I'm fine again." },
      { de: "Pero la cita no la olvido.", en: "But I won't forget the appointment." },
    ],
  },
  {
    id: "built-in-es-piso",
    title: "Buscar un piso",
    topicEn: "Housing",
    language: "es",
    level: "B1",
    vocab: [
      { term: "el alquiler", en: "rent" },
      { term: "los gastos", en: "bills" },
      { term: "la visita", en: "viewing" },
      { term: "la propietaria", en: "owner, landlady" },
      { term: "el contrato", en: "contract" },
      { term: "la fianza", en: "deposit" },
    ],
    lines: [
      { de: "En primavera busqué un piso nuevo.", en: "In spring I looked for a new flat." },
      { de: "En mi ciudad eso no es nada fácil.", en: "In my city that isn't easy at all." },
      { de: "Mucha gente busca y hay pocos pisos.", en: "Many people are looking and there are few flats." },
      { de: "El alquiler ha subido mucho estos años.", en: "Rents have risen a lot in recent years." },
      { de: "Por un piso pequeño pagas un alquiler alto.", en: "For a small flat you pay a high rent." },
      { de: "Mi alquiler anterior era bajo, por suerte.", en: "My previous rent was low, luckily." },
      { de: "También hay que mirar los gastos.", en: "You also have to look at the bills." },
      { de: "Los gastos incluyen agua, luz y basura.", en: "The bills include water, electricity and rubbish." },
      { de: "Sin los gastos todo parece barato.", en: "Without the bills everything looks cheap." },
      { de: "Escribí a veinte anuncios en internet.", en: "I wrote to twenty adverts online." },
      { de: "Solo cuatro personas me contestaron.", en: "Only four people answered me." },
      { de: "Luego tuve mi primera visita.", en: "Then I had my first viewing." },
      { de: "En una visita había treinta personas más.", en: "At one viewing there were thirty other people." },
      { de: "Después de esa visita estaba agotada.", en: "After that viewing I was exhausted." },
      { de: "¿Tú también estás buscando piso?", en: "Are you looking for a flat too?" },
      { de: "Con el cuarto piso tuve suerte.", en: "With the fourth flat I was lucky." },
      { de: "La propietaria era amable y tranquila.", en: "The owner was friendly and calm." },
      { de: "La propietaria quería ver mi contrato de trabajo.", en: "The owner wanted to see my employment contract." },
      { de: "Una propietaria pregunta casi siempre por el sueldo.", en: "An owner almost always asks about your salary." },
      { de: "Después llegó el contrato de alquiler.", en: "Then the rental contract came." },
      { de: "Leí el contrato dos veces.", en: "I read the contract twice." },
      { de: "El contrato hablaba de animales y de ruido.", en: "The contract talked about pets and noise." },
      { de: "Antes de la mudanza pagué una fianza.", en: "Before the move I paid a deposit." },
      { de: "La fianza era de dos meses de alquiler.", en: "The deposit was two months' rent." },
      { de: "Al final te devuelven la fianza.", en: "In the end they give the deposit back." },
      { de: "Pero solo si el piso está en buen estado.", en: "But only if the flat is in good condition." },
      { de: "Ahora vivo aquí desde hace tres meses.", en: "Now I've been living here for three months." },
      { de: "El balcón es pequeño, pero por la tarde da el sol.", en: "The balcony is small, but in the afternoon the sun comes in." },
      { de: "Y eso valió toda la búsqueda.", en: "And that made the whole search worth it." },
    ],
  },
  {
    id: "built-in-es-teletrabajo",
    title: "Trabajar desde casa",
    topicEn: "Work and jobs",
    language: "es",
    level: "B2",
    vocab: [
      { term: "el teletrabajo", en: "working from home" },
      { term: "el desplazamiento", en: "commute" },
      { term: "la reunión", en: "meeting" },
      { term: "concentrarse", en: "to concentrate" },
      { term: "el límite", en: "boundary" },
      { term: "desconectar", en: "to switch off" },
    ],
    lines: [
      { de: "Llevo cuatro años haciendo teletrabajo.", en: "I've been working from home for four years." },
      { de: "Al principio el teletrabajo parecía un sueño.", en: "At first working from home seemed like a dream." },
      { de: "Hoy veo el teletrabajo de forma más realista.", en: "Today I see working from home more realistically." },
      { de: "Lo mejor es que desaparece el desplazamiento.", en: "The best thing is that the commute disappears." },
      { de: "Antes el desplazamiento me costaba dos horas diarias.", en: "The commute used to cost me two hours a day." },
      { de: "Sin desplazamiento duermo más y como mejor.", en: "Without the commute I sleep more and eat better." },
      { de: "En cambio, el día está lleno de reuniones.", en: "On the other hand, the day is full of meetings." },
      { de: "Una reunión en línea es más corta pero más dura.", en: "An online meeting is shorter but harder." },
      { de: "Después de la quinta reunión tengo la cabeza vacía.", en: "After the fifth meeting my head is empty." },
      { de: "Por la mañana consigo concentrarme bien.", en: "In the morning I manage to concentrate well." },
      { de: "Por la tarde concentrarme me cuesta mucho más.", en: "In the afternoon concentrating is much harder for me." },
      { de: "Para concentrarse hace falta una puerta.", en: "To concentrate you need a door." },
      { de: "¿Tú también trabajas desde casa?", en: "Do you work from home too?" },
      { de: "El problema más grande es el límite.", en: "The biggest problem is the boundary." },
      { de: "El límite entre trabajo y vida privada desaparece rápido.", en: "The line between work and private life disappears fast." },
      { de: "Sin un límite claro sigues trabajando por la noche.", en: "Without a clear boundary you keep working at night." },
      { de: "Por eso intento desconectar a una hora fija.", en: "That's why I try to switch off at a fixed time." },
      { de: "Desconectar significa cerrar el portátil y apagar la luz.", en: "Switching off means closing the laptop and turning off the light." },
      { de: "Después de desconectar salgo a caminar.", en: "After switching off I go out for a walk." },
      { de: "Ese paseo sustituye mi antiguo desplazamiento.", en: "That walk replaces my old commute." },
      { de: "Una vez por semana voy a la oficina.", en: "Once a week I go to the office." },
      { de: "Allí una reunión se convierte en una conversación.", en: "There a meeting turns into a conversation." },
      { de: "Se habla del tiempo y de los proyectos.", en: "You talk about the weather and about projects." },
      { de: "Luego en casa me concentro mejor.", en: "Then at home I concentrate better." },
      { de: "La mezcla de las dos cosas me funciona.", en: "The mix of the two works for me." },
      { de: "El teletrabajo no es un sueño ni un problema.", en: "Working from home is neither a dream nor a problem." },
      { de: "Es simplemente una manera de trabajar.", en: "It's simply a way of working." },
      { de: "¿Y tú, dónde pones tu límite?", en: "And you, where do you draw your line?" },
    ],
  },
];

/** True for an episode that ships with the app rather than being generated. */
export function isBuiltIn(episode: PodcastEpisode): boolean {
  return episode.createdISO === undefined;
}

export function builtInEpisodes(language: Language): PodcastEpisode[] {
  return BUILT_IN_EPISODES.filter((episode) => episode.language === language);
}

/** Distance in CEFR steps, for sorting the shelf around the learner's level. */
export function levelDistance(a: Level, b: Level): number {
  const order: Level[] = ['A1', 'A2', 'B1', 'B2'];
  return Math.abs(order.indexOf(a) - order.indexOf(b));
}
